### ISSUE TITLE
TypeError: Outputs must be theano Variable or Out instances. Received [Subtensor{int64::}.0] of type <class 'list'>

### ISSUE THREAD

**Issue by alanyannick** [chrischoy/3D-R2N2#4]
Hi,

I am meeting the following problem, and whatever i try to use the different versions beyond python-3.5.1 like you said before in the last issue , or run by the version of PYTHON_CONFIGURE_OPTS="--enable-shared", it still doesn't work :(
```
Traceback (most recent call last):
  File "demo.py", line 84, in <module>
    main()
  File "demo.py", line 66, in main
    voxel_prediction, _ = solver.test_output(demo_imgs)
  File "/home/wenyangming/3D-R2N2/lib/solver.py", line 218, in test_output
    self.net.activations])
  File "/home/wenyangming/.pyenv/versions/env3_5_1/lib/python3.5/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/wenyangming/.pyenv/versions/env3_5_1/lib/python3.5/site-packages/theano/compile/pfunc.py", line 442, in pfunc
    no_default_updates=no_default_updates)
  File "/home/wenyangming/.pyenv/versions/env3_5_1/lib/python3.5/site-packages/theano/compile/pfunc.py", line 227, in rebuild_collect_shared
    ' of type ' + str(type(v)))
TypeError: Outputs must be theano Variable or Out instances. Received [Subtensor{int64::}.0] of type <class 'list'>
****
```
Did you have some suggestions for this problem?
Thanks a lot and looking forward to your response.

**Comment by abhi-kumar** [comment]
Is this issue solved?

**Comment by Artifineuro** [comment]
I came across this issue as well, has it been solved already? How to solve it?

**Comment by chrischoy** [comment]
Seems like the issue is resolved using the correct version.

If you prefer not to use anaconda, you can use lightweight python 3.6 virtual environment by following the instruction on https://github.com/chrischoy/python-venv-setup.

Closing the issue.

**Comment by michantia** [comment]
I have the same issue as alanyannick.

I tried a python 3.5 and python 3.6 environment in Anaconda. It still doesn't work. Any tips for anybody who found a different solution?

Thanks.
